---
params:
  train_itr: 4.0e+5   # Number of training iterations
  eval_itr: 5000   # Number of evaluation iterations
  eval_cycle: 1   # Evaluation cycle at each the algorithm is evaluated eval_itr times
  do_train: true    # Train or not
  do_taskset_eval: true   # Taskset evaluation
  do_cpu_load_eval: true
  do_task_size_eval: true
  do_channel_eval: true

  # DVFS algorithms parameters
  dqn_state_dim: 6
  batch_size: 32
  gamma: 0.95
  lr: 5.0e-4
  mem_size: 10000
  update_target_net: 1000
  eps_decay: 0.05
  min_eps: 0.01
  reward_coeff: 0.1
  deadline_missed_penalty: 2.0e+2
  latency_energy_coeff: 0

  num_tasks: 4
  target_cpu_load: 0.35
  min_task_load_train: 0.1
  max_task_load_train: 2
  min_task_load_eval: 0.1
  max_task_load_eval: 2
  min_task_size: 120
  max_task_size: 480
  min_cn_power: 1.0e-11
  max_cn_power: 1.0e-7
tasks:
  eval_1: configs/tasks/eval_1.yaml
  eval_2: configs/tasks/eval_2.yaml
  eval_3: configs/tasks/eval_3.yaml
  train: configs/tasks/train.yaml
cpus:
  little: configs/cpus/little.yaml
  big: configs/cpus/big.yaml
w_inter: configs/channel/wireless_inter.yaml
