---
params:
  train_itr: 4.0e+5 # Number of training iterations
  eval_itr: 5000 # Number of evaluation iterations
  eval_cycle: 1 # Evaluation cycle at each the algorithm is evaluated eval_itr times
  do_train: false # Train or not
  do_taskset_eval: true # Taskset evaluation
  do_cpu_load_eval: true # CPU load evaluation
  do_task_size_eval: true # Task size evaluation
  do_channel_eval: true  # Channel evaluation

  # DVFS algorithms parameters
  dqn_state_dim: 6 # State dimension for DQN (iDEAS)
  batch_size: 32 # Training batch size
  gamma: 0.95 # Discount factor
  lr: 1.0e-4 # Learning rate
  mem_size: 10000 # Replay buffer memory size
  update_target_net: 1000 # Steps at which target network is updated
  eps_decay: 0.005 # Epsilon decay rate
  min_eps: 0.02 # Minimum epsilon value
  reward_coeff: 0.1 # Reward coefficient to convert penalty to
  deadline_missed_penalty: 2.0e+2 # Penalty for deadline misses
  latency_energy_coeff: 0 # Coefficient to balance latency and energy values

  # Eval taskset parameters
  num_tasks: 4 # Number of tasks in the taskset
  target_cpu_load: 0.35 # Target CPU load
  min_task_load_train: 0 # Minimum task load for training
  max_task_load_train: 9 # Maximum task load for training
  min_task_load_eval: 0.1 # Minimum task load for evaluation
  max_task_load_eval: 9 # Maximum task load for evaluation
  min_task_size: 120 # Minimum task size
  max_task_size: 480 # Maximum task size
  min_cn_power: 1.0e-7 # Minimum channel noise power
  max_cn_power: 1.0e-4 # Maximum channel noise power
tasks:
  eval_1: configs/tasks/eval_1.yaml
  eval_2: configs/tasks/eval_2.yaml
  eval_3: configs/tasks/eval_3.yaml
  train: configs/tasks/train.yaml
cpus:
  little: configs/cpus/little.yaml
  big: configs/cpus/big.yaml
w_inter: configs/channel/wireless_inter.yaml
